/**
 * Orama-based hybrid search engine for property specification chunks.
 *
 * Combines BM25 full-text search with vector similarity search using
 * embeddings generated by the Web Worker. Documents are stored in-memory
 * with the schema: { id, section, content, embedding }.
 */
import {
  create,
  insert,
  search,
  type AnyOrama,
  type SearchParams,
} from "@orama/orama";
import type { PropertyChunk, RetrievedChunk } from "../types/rag";

const EMBEDDING_DIMENSIONS = 384; // all-MiniLM-L6-v2 produces 384-dim vectors

let db: AnyOrama | null = null;

/**
 * Initialize the Orama in-memory database with the property chunk schema.
 */
export async function initSearchEngine(): Promise<void> {
  db = await create({
    schema: {
      id: "string",
      section: "string",
      content: "string",
      embedding: `vector[${EMBEDDING_DIMENSIONS}]`,
    } as const,
  });
}

/**
 * Insert pre-embedded property chunks into the Orama database.
 */
export async function indexChunks(chunks: PropertyChunk[]): Promise<void> {
  if (!db) throw new Error("Search engine not initialized");

  for (const chunk of chunks) {
    await insert(db, {
      id: chunk.id,
      section: chunk.section,
      content: chunk.content,
      embedding: chunk.embedding,
    });
  }
}

/**
 * Perform hybrid search: BM25 full-text match combined with vector similarity.
 * Returns the top-k most relevant chunks.
 */
export async function hybridSearch(
  query: string,
  queryEmbedding: number[],
  topK = 3,
): Promise<RetrievedChunk[]> {
  if (!db) throw new Error("Search engine not initialized");

  const params: SearchParams<AnyOrama, unknown> = {
    term: query,
    properties: ["content", "section"],
    vector: {
      value: queryEmbedding,
      property: "embedding",
    },
    similarity: 0.3, // minimum similarity threshold
    limit: topK,
  };

  const results = await search(db, params);

  return results.hits.map((hit) => {
    const doc = hit.document as Record<string, unknown>;
    return {
      section: doc.section as string,
      content: doc.content as string,
      score: hit.score,
    };
  });
}

/**
 * Reset the search engine (useful for re-indexing with new property data).
 */
export async function resetSearchEngine(): Promise<void> {
  db = null;
  await initSearchEngine();
}
