const VERSION_STORAGE_KEY = "matterport-master-builder.version.v1";
const DEFAULT_VERSION_STATE = { major: 1, minor: 2, lastExportedVersion: "", lastExportedAt: "" };
const DEFAULT_BEHAVIOR_STATE = {
    hideBranding: false,
    mlsModeEnabled: false,
    mlsModeValue: "1",
    hideTitle: false,
    autoPlay: true,
    quickstart: false,
    autoStartTour: false,
    autoStartTourDelay: "8",
    loopGuidedTour: false,
    hideDollhouse: false,
    hideHighlightReel: false,
    singleFloorFocus: false,
    hideMattertags: false,
    hideSearch: false,
    disableScrollWheelZoom: true,
    disableZoom: false,
    forceLanguage: false,
    languageCode: "en",
    hideGuidedPath: false,
    transitionEnabled: false,
    transitionValue: "2",
    customParams: "",
};
const TOUR_BEHAVIOR_GROUPS = [
    {
        title: "Brand Control and Professionalism",
        description: "Reduce Matterport chrome and create cleaner branded or MLS-safe presentation modes.",
        options: [
            {
                key: "hideBranding",
                param: "brand",
                fixedValue: "0",
                label: "Hide Matterport Branding",
                summary: "Hide Branding",
                description: "Removes Matterport-presented branding details for a cleaner white-label experience.",
            },
            {
                key: "mlsModeEnabled",
                param: "mls",
                label: "MLS Compliance Mode",
                summary: "MLS Mode",
                description: "Turns on MLS-safe suppression of branding and interface elements for listing compliance.",
                control: {
                    key: "mlsModeValue",
                    type: "select",
                    label: "Compliance level",
                    defaultValue: "1",
                    choices: [
                        { value: "1", label: "MLS 1 | Remove branding and links" },
                        { value: "2", label: "MLS 2 | Also hide the About panel" },
                    ],
                },
            },
            {
                key: "hideTitle",
                param: "title",
                fixedValue: "0",
                label: "Hide Space Title",
                summary: "Hide Space Title",
                description: "Removes the title and top-left panel space for a more minimal fullscreen presentation.",
            },
        ],
    },
    {
        title: "Guided Experience and Automatic Motion",
        description: "Control how quickly people enter the model and whether a guided tour begins on its own.",
        options: [
            {
                key: "autoPlay",
                param: "play",
                fixedValue: "1",
                label: "Auto-Play",
                summary: "Auto-Play",
                description: "Bypasses the initial Matterport play gate so visitors land inside the tour immediately.",
            },
            {
                key: "quickstart",
                param: "qs",
                fixedValue: "1",
                label: "Quickstart",
                summary: "Quickstart",
                description: "Skips the dollhouse fly-in animation and opens directly in the inside view.",
            },
            {
                key: "autoStartTour",
                param: "ts",
                label: "Auto-Start Guided Tour",
                summary: "Auto-Start Tour",
                description: "Starts the guided highlight reel automatically after a chosen number of seconds.",
                control: {
                    key: "autoStartTourDelay",
                    type: "number",
                    label: "Delay in seconds",
                    min: "0",
                    step: "1",
                    defaultValue: "8",
                    placeholder: "8",
                },
            },
            {
                key: "loopGuidedTour",
                param: "lp",
                fixedValue: "1",
                label: "Loop Guided Tour",
                summary: "Loop Guided Tour",
                description: "Loops the guided tour continuously for kiosks, tablets, open houses, and showroom screens.",
            },
        ],
    },
    {
        title: "Interface and Navigation Customization",
        description: "Hide specific UI controls so the tour feels more cinematic and less cluttered.",
        options: [
            {
                key: "hideDollhouse",
                param: "dh",
                fixedValue: "0",
                label: "Hide Dollhouse",
                summary: "Hide Dollhouse",
                description: "Removes dollhouse access when the exterior mesh is distracting or unnecessary.",
            },
            {
                key: "hideHighlightReel",
                param: "hr",
                fixedValue: "0",
                label: "Hide Highlight Reel",
                summary: "Hide Highlight Reel",
                description: "Hides the thumbnail strip to encourage a cleaner, self-guided walkthrough.",
            },
            {
                key: "singleFloorFocus",
                param: "f",
                fixedValue: "0",
                label: "Single Floor Focus",
                summary: "Single Floor Focus",
                description: "Removes the floor switcher for simple single-level properties or condo presentations.",
            },
            {
                key: "hideMattertags",
                param: "mt",
                fixedValue: "0",
                label: "Hide Mattertags",
                summary: "Hide Mattertags",
                description: "Starts the tour with Mattertags hidden so rooms feel cleaner before details are explored.",
            },
            {
                key: "hideSearch",
                param: "search",
                fixedValue: "0",
                label: "Hide Search",
                summary: "Hide Search",
                description: "Removes the Mattertag search icon for a more minimal residential viewer experience.",
            },
        ],
    },
    {
        title: "User Experience and Embedding Optimization",
        description: "Tune motion, scrolling, and localization so the embed behaves well on landing pages and global campaigns.",
        options: [
            {
                key: "disableScrollWheelZoom",
                param: "wh",
                fixedValue: "0",
                label: "Disable Scroll Wheel Zoom",
                summary: "Disable Scroll Wheel Zoom",
                description: "Prevents scroll-trap behavior so page scrolling works normally around the embedded tour.",
            },
            {
                key: "disableZoom",
                param: "nozoom",
                fixedValue: "1",
                label: "Disable Zoom",
                summary: "Disable Zoom",
                description: "Locks zoom to preserve polish and stop visitors from pushing into low-resolution details.",
            },
            {
                key: "forceLanguage",
                param: "lang",
                label: "Force UI Language",
                summary: "Forced Language",
                description: "Forces the Matterport viewer interface into a chosen language code for global audiences.",
                control: {
                    key: "languageCode",
                    type: "text",
                    label: "Language code",
                    defaultValue: "en",
                    placeholder: "fr / es / en",
                },
            },
        ],
    },
    {
        title: "Hidden and Advanced Techniques",
        description: "Refine the automated path and transition style, or combine these presets with custom deep-link parameters.",
        options: [
            {
                key: "hideGuidedPath",
                param: "guidedpath",
                fixedValue: "0",
                label: "Hide Guided Path",
                summary: "Hide Guided Path",
                description: "Suppresses the blue path markers during automated tours for a smoother cinematic feel.",
            },
            {
                key: "transitionEnabled",
                param: "transition",
                label: "Transition Style",
                summary: "Transition Style",
                description: "Choose between Matterport's walking transition and a cleaner 2D fade between points.",
                control: {
                    key: "transitionValue",
                    type: "select",
                    label: "Transition mode",
                    defaultValue: "2",
                    choices: [
                        { value: "1", label: "Style 1 | 3D walking transition" },
                        { value: "2", label: "Style 2 | 2D fade transition" },
                    ],
                },
            },
        ],
    },
];
const TOUR_BEHAVIOR_OPTIONS = TOUR_BEHAVIOR_GROUPS.flatMap((group) => group.options);
const SUPPORTED_UPLOAD_IMAGE_MIME_TYPES = new Set([
    "image/png",
    "image/jpeg",
    "image/svg+xml",
    "image/webp",
]);
const SUPPORTED_UPLOAD_IMAGE_EXTENSIONS = new Set(["png", "jpg", "jpeg", "svg", "webp"]);
const SUPPORTED_UPLOAD_IMAGE_LABEL = "PNG, JPG, SVG, or WebP";
